### ISSUE TITLE
Whisper Example on ORT master

### ISSUE THREAD

**Issue by sspintel** [microsoft/Olive#293]
The documentation specifies that we still use a specific nightly build of ORT to optimize the Whisper model. However, the dummy input issue of https://github.com/microsoft/onnxruntime/pull/15936 and https://github.com/microsoft/onnxruntime/commit/e5189330d591d48d34cb08aa6f144141419217f2 is blocking execution of the optimized model through the OpenVINO Execution Provider for the same reason i.e, OpenVINO model compilation removes any dummy inputs in the graph but since it is present in the Olive optimized model (through the ORT 1.15 nightly), it fails to go through. Hence, OVEP requires the fixes for the dummy input issue in ORT master.

When I use ORT master to optimize Whisper through Olive, I get this error

`out = model(inputs.encoder_input_ids, inputs.encoder_attention_mask, inputs.decoder_input_ids)
AttributeError: 'WhisperEncoderDecoderInitInputs' object has no attribute 'encoder_attention_mask'`

**Comment by jambayk** [comment]
Thanks for opening this issue. There was a recent change in the ORT that makes the `user_script.py` in the whisper example incompatible with the nightly version. The user script only works with ORT version up to version 1.15.0 and the specific version of ORT nightly in the example was for `1.15.0dev`. 

I have updated the README and dependencies to version 1.15.0 in this PR https://github.com/microsoft/Olive/pull/305 

If required, I might be able to update the user script to support ORT versions > 1.15.0.

**Comment by sspintel** [comment]
Hi @jambayk

Thanks for the response. Is it possible to update the user script as you suggested to support ORT > 1.15?
